/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kkmofang_duktape_Context */

#ifndef _Included_cn_kkmofang_duktape_Context
#define _Included_cn_kkmofang_duktape_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_kkmofang_duktape_Context_alloc
  (JNIEnv *, jclass);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_dealloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushobject
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushobject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushfunction
 * Signature: (JLcn/kkmofang/duktape/Function;)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushfunction
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushstring
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushstring
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushnumber
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushnumber
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushinteger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushinteger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pushboolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pushboolean
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    gettype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_kkmofang_duktape_Context_gettype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    gettop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_kkmofang_duktape_Context_gettop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    toobject
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cn_kkmofang_duktape_Context_toobject
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    tostring
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_kkmofang_duktape_Context_tostring
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    tonumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_kkmofang_duktape_Context_tonumber
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    tointeger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cn_kkmofang_duktape_Context_tointeger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    toboolean
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_kkmofang_duktape_Context_toboolean
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_kkmofang_duktape_Context
 * Method:    pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cn_kkmofang_duktape_Context_pop
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
